"""add competency domain tables

Revision ID: 10c9612cbd58
Revises: 2a64b9b10cf7
Create Date: 2026-06-23 11:32:49.299989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10c9612cbd58'
down_revision: Union[str, Sequence[str], None] = '2a64b9b10cf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competency_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('domain', sa.String(length=32), nullable=False),
    sa.Column('subdomain', sa.String(length=64), nullable=True),
    sa.Column('skill', sa.String(length=24), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cefr_level_hint', sa.String(length=2), nullable=False),
    sa.Column('performance_descriptors', sa.JSON(), nullable=False),
    sa.Column('positive_patterns', sa.JSON(), nullable=False),
    sa.Column('negative_patterns', sa.JSON(), nullable=False),
    sa.Column('exceptions', sa.JSON(), nullable=False),
    sa.Column('evidence_required', sa.Integer(), nullable=False),
    sa.Column('accuracy_threshold', sa.Float(), nullable=False),
    sa.Column('contexts_required', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('competency_definitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_competency_definitions_cefr_level_hint'), ['cefr_level_hint'], unique=False)
        batch_op.create_index(batch_op.f('ix_competency_definitions_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_competency_definitions_domain'), ['domain'], unique=False)

    op.create_table('evaluation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evaluator_type', sa.String(length=40), nullable=False),
    sa.Column('model_provider', sa.String(length=32), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=True),
    sa.Column('prompt_version', sa.String(length=32), nullable=True),
    sa.Column('input_hash', sa.String(length=64), nullable=True),
    sa.Column('raw_input', sa.Text(), nullable=True),
    sa.Column('raw_output', sa.Text(), nullable=True),
    sa.Column('parsed_output', sa.JSON(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evaluation_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluation_runs_input_hash'), ['input_hash'], unique=False)

    op.create_table('cefr_projections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('learner_id', sa.Integer(), nullable=False),
    sa.Column('grammar_level', sa.String(length=2), nullable=True),
    sa.Column('vocabulary_level', sa.String(length=2), nullable=True),
    sa.Column('speaking_level', sa.String(length=2), nullable=True),
    sa.Column('listening_level', sa.String(length=2), nullable=True),
    sa.Column('reading_level', sa.String(length=2), nullable=True),
    sa.Column('writing_level', sa.String(length=2), nullable=True),
    sa.Column('communication_level', sa.String(length=2), nullable=True),
    sa.Column('overall_level', sa.String(length=2), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('algorithm_version', sa.String(length=32), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cefr_projections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cefr_projections_learner_id'), ['learner_id'], unique=False)

    op.create_table('competency_prerequisites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competency_id', sa.Integer(), nullable=False),
    sa.Column('prerequisite_competency_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sa.String(length=16), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['competency_id'], ['competency_definitions.id'], ),
    sa.ForeignKeyConstraint(['prerequisite_competency_id'], ['competency_definitions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('competency_id', 'prerequisite_competency_id', name='uq_competency_prereq')
    )
    with op.batch_alter_table('competency_prerequisites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_competency_prerequisites_competency_id'), ['competency_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_competency_prerequisites_prerequisite_competency_id'), ['prerequisite_competency_id'], unique=False)

    op.create_table('evidence_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('learner_id', sa.Integer(), nullable=False),
    sa.Column('competency_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('activity_type', sa.String(length=32), nullable=True),
    sa.Column('context_key', sa.String(length=64), nullable=False),
    sa.Column('modality', sa.String(length=16), nullable=False),
    sa.Column('observed_text', sa.Text(), nullable=True),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('correctness_score', sa.Float(), nullable=False),
    sa.Column('evaluator_confidence', sa.Float(), nullable=False),
    sa.Column('evidence_weight', sa.Float(), nullable=False),
    sa.Column('detected_error', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('prompt_version', sa.String(length=32), nullable=True),
    sa.Column('evaluator_version', sa.String(length=32), nullable=True),
    sa.Column('model_name', sa.String(length=64), nullable=True),
    sa.Column('evaluation_run_id', sa.Integer(), nullable=True),
    sa.Column('human_review_status', sa.String(length=16), nullable=False),
    sa.Column('human_override', sa.JSON(), nullable=True),
    sa.Column('observed_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['competency_id'], ['competency_definitions.id'], ),
    sa.ForeignKeyConstraint(['evaluation_run_id'], ['evaluation_runs.id'], ),
    sa.ForeignKeyConstraint(['learner_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence_observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_observations_competency_id'), ['competency_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_observations_evaluation_run_id'), ['evaluation_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_observations_human_review_status'), ['human_review_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_observations_learner_id'), ['learner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_observations_source_type'), ['source_type'], unique=False)
        batch_op.create_index('ix_obs_learner_competency', ['learner_id', 'competency_id'], unique=False)
        batch_op.create_index('ix_obs_source', ['source_type', 'source_id'], unique=False)

    op.create_table('learner_competencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('learner_id', sa.Integer(), nullable=False),
    sa.Column('competency_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('valid_evidence_count', sa.Integer(), nullable=False),
    sa.Column('distinct_context_count', sa.Integer(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('weighted_accuracy', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('first_observed_at', sa.DateTime(), nullable=True),
    sa.Column('last_observed_at', sa.DateTime(), nullable=True),
    sa.Column('mastered_at', sa.DateTime(), nullable=True),
    sa.Column('algorithm_version', sa.String(length=32), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['competency_id'], ['competency_definitions.id'], ),
    sa.ForeignKeyConstraint(['learner_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('learner_id', 'competency_id', name='uq_learner_competency')
    )
    with op.batch_alter_table('learner_competencies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learner_competencies_competency_id'), ['competency_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_learner_competencies_learner_id'), ['learner_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learner_competencies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learner_competencies_learner_id'))
        batch_op.drop_index(batch_op.f('ix_learner_competencies_competency_id'))

    op.drop_table('learner_competencies')
    with op.batch_alter_table('evidence_observations', schema=None) as batch_op:
        batch_op.drop_index('ix_obs_source')
        batch_op.drop_index('ix_obs_learner_competency')
        batch_op.drop_index(batch_op.f('ix_evidence_observations_source_type'))
        batch_op.drop_index(batch_op.f('ix_evidence_observations_learner_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_observations_human_review_status'))
        batch_op.drop_index(batch_op.f('ix_evidence_observations_evaluation_run_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_observations_competency_id'))

    op.drop_table('evidence_observations')
    with op.batch_alter_table('competency_prerequisites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_competency_prerequisites_prerequisite_competency_id'))
        batch_op.drop_index(batch_op.f('ix_competency_prerequisites_competency_id'))

    op.drop_table('competency_prerequisites')
    with op.batch_alter_table('cefr_projections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cefr_projections_learner_id'))

    op.drop_table('cefr_projections')
    with op.batch_alter_table('evaluation_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluation_runs_input_hash'))

    op.drop_table('evaluation_runs')
    with op.batch_alter_table('competency_definitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_competency_definitions_domain'))
        batch_op.drop_index(batch_op.f('ix_competency_definitions_code'))
        batch_op.drop_index(batch_op.f('ix_competency_definitions_cefr_level_hint'))

    op.drop_table('competency_definitions')
    # ### end Alembic commands ###
