"""baseline existing assessment schema

Revision ID: 2a64b9b10cf7
Revises: 
Create Date: 2026-06-23 11:21:21.646459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a64b9b10cf7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('cefr_level', sa.String(length=2), nullable=False),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('format', sa.String(length=8), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exams_cefr_level'), ['cefr_level'], unique=False)

    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=True),
    sa.Column('skill', sa.String(length=16), nullable=False),
    sa.Column('cefr_level', sa.String(length=2), nullable=False),
    sa.Column('topic', sa.String(length=120), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('expected_patterns', sa.JSON(), nullable=True),
    sa.Column('sample_response', sa.Text(), nullable=True),
    sa.Column('rubric', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('format', sa.String(length=8), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_items_cefr_level'), ['cefr_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_skill'), ['skill'], unique=False)
        batch_op.create_index('ix_items_skill_level', ['skill', 'cefr_level', 'active'], unique=False)

    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('l1', sa.String(length=8), nullable=False),
    sa.Column('cefr_level', sa.String(length=2), nullable=False),
    sa.Column('goal', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_students_cefr_level'), ['cefr_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_students_external_id'), ['external_id'], unique=False)

    op.create_table('exam_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('final_band', sa.String(length=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exam_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exam_sessions_exam_id'), ['exam_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exam_sessions_student_id'), ['student_id'], unique=False)

    op.create_table('answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=False),
    sa.Column('response_audio_path', sa.String(length=255), nullable=True),
    sa.Column('raw_llm_output', sa.JSON(), nullable=True),
    sa.Column('band', sa.String(length=2), nullable=True),
    sa.Column('scores', sa.JSON(), nullable=True),
    sa.Column('feedback_student', sa.Text(), nullable=True),
    sa.Column('feedback_internal', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('flagged_for_review', sa.Boolean(), nullable=False),
    sa.Column('reviewer_override_band', sa.String(length=2), nullable=True),
    sa.Column('reviewer_override_scores', sa.JSON(), nullable=True),
    sa.Column('reviewer_note', sa.Text(), nullable=True),
    sa.Column('reviewer_id', sa.String(length=64), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['exam_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_answers_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_answers_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_answers_session_id'))
        batch_op.drop_index(batch_op.f('ix_answers_item_id'))

    op.drop_table('answers')
    with op.batch_alter_table('exam_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exam_sessions_student_id'))
        batch_op.drop_index(batch_op.f('ix_exam_sessions_exam_id'))

    op.drop_table('exam_sessions')
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_external_id'))
        batch_op.drop_index(batch_op.f('ix_students_cefr_level'))

    op.drop_table('students')
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_index('ix_items_skill_level')
        batch_op.drop_index(batch_op.f('ix_items_skill'))
        batch_op.drop_index(batch_op.f('ix_items_code'))
        batch_op.drop_index(batch_op.f('ix_items_cefr_level'))

    op.drop_table('items')
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exams_cefr_level'))

    op.drop_table('exams')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
